# Set re-inject host from environment (POSTFIX_HOST=mailhub-postfix from stack)
if ($ENV{'POSTFIX_HOST'}) {
  $forward_method = 'smtp:[' . $ENV{'POSTFIX_HOST'} . ']:10025';
  $notify_method = $forward_method;
}
1;
