# -*- coding: utf-8 -*-
"""Emit scripts/recipe-pdf-ingredients-data.mjs — keys match Recipe/Text/PDF/*.txt exactly."""
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "recipe-pdf-ingredients-data.mjs"
PDF_DIR = ROOT.parent / "Recipe" / "Text" / "PDF"

# Reference-only PDFs (manuals / collections); no curated recipe rows.
SKIP = {
    "DUO-Series-Manual-English-January-24-2018-web.txt",
    "IP_for_Beginners.txt",
    "Indian Recipes.txt",
    "Vegetable Recipes.txt",
    "Salads Recipes.txt",
}

# Recipes in sorted-filename order (see scripts/pdf-import-order.txt).
RECIPES = [
    {
        "name": "15 Bean Sloppy Joes (Hurst)",
        "servings": 12,
        "ingredients": [
            [1, "package", "Hurst 15 Bean Soup mix, beef flavored"],
            [1, "Pound", "Ground beef"],
            [1, "Cup", "Yellow onion, diced"],
            [1, "Cup", "Green bell pepper, diced"],
            [1, "Cup", "Tomato ketchup"],
            [0.5, "Cup", "Yellow mustard"],
            [1, "Tablespoon", "Apple cider vinegar"],
            [2, "Teaspoon", "Chili powder"],
            [1, "Tablespoon", "Brown sugar"],
            [3, "cloves", "Garlic, chopped"],
            [6, "Cup", "Water"],
        ],
    },
    {
        "name": "30-Minute Chinese Crispy Beef",
        "servings": 4,
        "ingredients": [
            [0.75, "Pound", "Beef sirloin steak, sliced"],
            [2, "Teaspoon", "Soy sauce, low-sodium"],
            [5, "Tablespoon", "Cornstarch"],
            [0.5, "each", "Carrot, matchstick"],
            [2, "each", "Scallions, sliced"],
            [1, "each", "Red chili, sliced"],
            [0.25, "Cup", "Vegetable oil, for frying"],
            [3, "Tablespoon", "Soy sauce, low-sodium"],
            [2, "Tablespoon", "Honey"],
            [2, "Tablespoon", "Sweet chili sauce"],
            [1, "Tablespoon", "Rice vinegar"],
            [3, "cloves", "Garlic, minced"],
            [1, "Teaspoon", "Cornstarch"],
        ],
    },
    {
        "name": "Apple Brown Betty",
        "servings": 8,
        "ingredients": [
            [5, "each", "Honeycrisp apples, peeled and sliced"],
            [2, "Tablespoon", "Lemon juice"],
            [0.75, "Cup", "All-purpose flour"],
            [0.67, "Cup", "Brown sugar"],
            [0.33, "Cup", "Sugar"],
            [1.5, "Teaspoon", "Cinnamon, ground"],
            [0.25, "Teaspoon", "Nutmeg, ground"],
            [0.125, "Teaspoon", "Cloves, ground"],
            [0.125, "Teaspoon", "Salt"],
            [0.5, "Cup", "Butter, cold"],
        ],
    },
    {
        "name": "Slow Cooker Pulled Pork",
        "servings": 8,
        "ingredients": [
            [4.5, "Pound", "Pork shoulder"],
            [2, "Tablespoon", "Paprika"],
            [1, "Teaspoon", "Oregano, dried"],
            [1, "Teaspoon", "Salt"],
            [1, "Teaspoon", "Black pepper"],
            [0.5, "Teaspoon", "Cumin"],
            [1, "each", "Yellow onion, diced"],
            [4, "cloves", "Garlic, chopped"],
            [1, "each", "Orange, juiced"],
        ],
    },
    {
        "name": "Instant Pot Beef Stew",
        "servings": 6,
        "ingredients": [
            [3, "Pound", "Beef stew meat"],
            [0.33, "Cup", "All-purpose flour"],
            [1, "Teaspoon", "Kosher salt"],
            [0.5, "Teaspoon", "Black pepper"],
            [3, "Tablespoon", "Vegetable oil"],
            [0.5, "Cup", "Red wine"],
            [1, "each", "Onion"],
            [2, "cloves", "Garlic"],
            [3, "each", "Carrots"],
            [2, "each", "Celery stalks"],
            [1, "Pound", "Red potatoes"],
            [1, "Tablespoon", "Tomato paste"],
            [2.5, "Cup", "Beef stock, reduced sodium"],
            [0.25, "Cup", "Italian parsley, chopped"],
        ],
    },
    {
        "name": "Instant Pot Beef and Barley Soup",
        "servings": 8,
        "ingredients": [
            [2, "Pound", "Beef chuck"],
            [4, "Teaspoon", "Olive oil"],
            [1, "each", "Sweet onion"],
            [1, "each", "Celery stalk"],
            [2, "cloves", "Garlic"],
            [2, "Cup", "Carrots"],
            [15, "Ounce", "Diced tomatoes, canned"],
            [3, "each", "Red potatoes"],
            [0.67, "Cup", "Pearl barley"],
            [6, "Cup", "Beef broth"],
            [1, "Teaspoon", "Salt"],
            [0.125, "Teaspoon", "Black pepper"],
            [2, "sprig", "Thyme"],
            [1, "each", "Bay leaves"],
            [1, "Cup", "Green beans, frozen"],
            [0.25, "Cup", "Parsley, fresh chopped"],
        ],
    },
    {
        "name": "Crock Pot Mississippi Pork Roast",
        "servings": 6,
        "ingredients": [
            [3, "Pound", "Pork roast, boneless"],
            [2, "Tablespoon", "Olive oil"],
            [1, "package", "Ranch dressing mix, dry"],
            [1, "package", "Onion soup mix, dry"],
            [0.5, "Cup", "Butter, salted"],
            [6, "each", "Peperoncini peppers"],
        ],
    },
    {
        "name": "Instant Pot Cheesecake",
        "servings": 8,
        "ingredients": [
            [1, "Cup", "Graham cracker crumbs"],
            [3, "Tablespoon", "Butter, melted"],
            [1, "pinch", "Salt"],
            [16, "Ounce", "Cream cheese"],
            [0.5, "Cup", "Sugar"],
            [0.25, "Cup", "Brown sugar"],
            [0.25, "Cup", "Sour cream"],
            [1, "Tablespoon", "All-purpose flour"],
            [1, "Teaspoon", "Vanilla extract"],
            [0.25, "Teaspoon", "Kosher salt"],
            [2, "each", "Eggs"],
            [1.5, "Cup", "Water"],
        ],
    },
    {
        "name": "Instant Pot Chicken Alfredo",
        "servings": 4,
        "ingredients": [
            [2, "each", "Chicken breast, boneless skinless"],
            [1, "Teaspoon", "Garlic powder"],
            [1, "Tablespoon", "Olive oil"],
            [2, "Tablespoon", "Butter"],
            [3, "cloves", "Garlic, minced"],
            [1.5, "Cup", "Heavy cream"],
            [0.5, "Cup", "Whole milk"],
            [2, "Cup", "Chicken broth, low-sodium"],
            [0.5, "Teaspoon", "Basil, dried"],
            [8, "Ounce", "Fettuccine noodles, dry"],
            [1, "Cup", "Parmesan cheese, grated"],
            [1, "Tablespoon", "Parsley, chopped"],
        ],
    },
    {
        "name": "Chicken Empanadas",
        "servings": 10,
        "ingredients": [
            [2, "Tablespoon", "Olive oil, extra virgin"],
            [0.5, "Cup", "Onion, minced"],
            [1, "each", "Red bell pepper, minced"],
            [1, "each", "Yellow bell pepper, minced"],
            [4, "cloves", "Garlic, minced"],
            [2, "Tablespoon", "Cilantro, minced"],
            [2, "Cup", "Chicken breast, shredded"],
            [2, "Teaspoon", "Chicken bouillon"],
            [1, "Tablespoon", "Tomato paste"],
            [1, "Teaspoon", "Onion powder"],
            [1, "Teaspoon", "Garlic powder"],
            [0.5, "Teaspoon", "Kosher salt"],
            [10, "each", "Empanada dough shells"],
            [1, "each", "Eggs"],
        ],
    },
    {
        "name": "Instant Pot Chicken Pot Roast",
        "servings": 4,
        "ingredients": [
            [3, "Pound", "Whole chicken"],
            [0.25, "Teaspoon", "Kosher salt"],
            [0.5, "Teaspoon", "Black pepper"],
            [0.5, "each", "Lemon"],
            [2, "sprig", "Rosemary"],
            [2, "Teaspoon", "Olive oil, extra virgin"],
            [1, "each", "Potato, halved"],
            [0.5, "Cup", "Onion, chopped"],
            [1, "each", "Celery stalk"],
            [1, "each", "Carrot, quartered"],
            [2, "cloves", "Garlic, sliced"],
            [1, "Cup", "Chicken broth, low-sodium"],
            [1, "Tablespoon", "Parsley, chopped"],
        ],
    },
    {
        "name": "Instant Pot Corned Beef and Cabbage",
        "servings": 6,
        "ingredients": [
            [1, "each", "Onion, wedged"],
            [2, "Pound", "Corned beef brisket"],
            [4, "Cup", "Chicken broth, low-sodium"],
            [1, "each", "Cabbage, small, wedged"],
            [1, "Pound", "Baby potatoes, halved"],
            [4, "each", "Carrots, sliced"],
            [3, "Tablespoon", "Olive oil"],
            [1, "Tablespoon", "Parsley, chopped"],
        ],
    },
    {
        "name": "Crispy Chilli Beef",
        "servings": 4,
        "ingredients": [
            [0.75, "Pound", "Sirloin steak, thin strips"],
            [1, "each", "Eggs"],
            [4, "Tablespoon", "Cornstarch"],
            [0.25, "Teaspoon", "Salt"],
            [0.25, "Teaspoon", "Black pepper"],
            [0.125, "Teaspoon", "White pepper"],
            [4.5, "Tablespoon", "Sunflower oil"],
            [1, "each", "Onion, sliced"],
            [1, "each", "Red chili, sliced"],
            [1, "Teaspoon", "Fresh ginger, minced"],
            [3, "cloves", "Garlic, minced"],
            [2, "Tablespoon", "Rice vinegar"],
            [3, "Tablespoon", "Soy sauce, dark"],
            [2, "Tablespoon", "Tomato puree"],
            [6, "Tablespoon", "Sugar, caster"],
            [2, "Tablespoon", "Tomato ketchup"],
            [2, "Tablespoon", "Sweet chili sauce"],
        ],
    },
    {
        "name": "Crispy Sticky Mongolian Beef",
        "servings": 3,
        "ingredients": [
            [8, "Ounce", "Beef steak, sliced"],
            [1, "Teaspoon", "Soy sauce"],
            [3, "Teaspoon", "Cornstarch"],
            [1, "Teaspoon", "Vegetable oil"],
            [0.25, "Cup", "Water"],
            [2, "Tablespoon", "Soy sauce"],
            [0.25, "Cup", "Chicken broth"],
            [1.5, "Tablespoon", "Chinese cooking wine"],
            [3, "Tablespoon", "Brown sugar"],
            [0.25, "Cup", "Vegetable oil, for frying"],
            [0.25, "Cup", "Cornstarch, for coating"],
            [0.5, "Teaspoon", "Fresh ginger, minced"],
            [2, "cloves", "Garlic, crushed"],
            [2, "each", "Scallions"],
        ],
    },
    {
        "name": "Dad's Egg Fried Rice",
        "servings": 4,
        "ingredients": [
            [14, "Ounce", "Jasmine rice, uncooked"],
            [14, "Ounce", "Water"],
            [1, "Ounce", "Green onion, green part only"],
            [2, "Ounce", "Carrot"],
            [4, "Ounce", "Frozen peas and corn"],
            [4, "each", "Eggs"],
            [1.5, "Teaspoon", "Salt"],
            [0.3, "Cup", "Water"],
            [3, "Tablespoon", "Vegetable oil"],
            [1, "Tablespoon", "Soy sauce, light"],
            [1, "Teaspoon", "Soy sauce, dark"],
            [0.5, "Teaspoon", "Sugar"],
            [1, "Teaspoon", "Chicken bouillon powder"],
        ],
    },
    {
        "name": "Easy Fried Rice",
        "servings": 4,
        "ingredients": [
            [2, "each", "Eggs"],
            [0.25, "Teaspoon", "Salt"],
            [3, "Tablespoon", "Canola oil"],
            [4, "Cup", "Rice, cooked"],
            [1.5, "Cup", "Frozen stir-fry vegetables"],
            [0.5, "Cup", "Green onions, sliced"],
            [1, "clove", "Garlic, minced"],
            [1, "Cup", "Chicken, cooked diced"],
            [3, "Tablespoon", "Soy sauce"],
            [1, "Tablespoon", "Chicken broth"],
            [0.5, "Teaspoon", "Black pepper"],
            [0.25, "Teaspoon", "Ginger, ground"],
            [4, "slices", "Bacon, cooked crumbled"],
        ],
    },
    {
        "name": "Easy Pad Thai",
        "servings": 4,
        "ingredients": [
            [4, "Ounce", "Rice noodles, dry thick"],
            [0.5, "Pound", "Pork tenderloin, sliced"],
            [2, "Teaspoon", "Canola oil"],
            [2, "each", "Shallots, sliced"],
            [2, "cloves", "Garlic, minced"],
            [1, "each", "Eggs"],
            [3, "Cup", "Coleslaw mix"],
            [4, "each", "Green onions, sliced"],
            [0.33, "Cup", "Rice vinegar"],
            [0.25, "Cup", "Sugar"],
            [3, "Tablespoon", "Soy sauce, reduced sodium"],
            [2, "Tablespoon", "Fish sauce"],
            [1, "Tablespoon", "Chili garlic sauce"],
            [1, "Tablespoon", "Lime juice"],
            [2, "Tablespoon", "Peanuts, chopped salted"],
        ],
    },
    {
        "name": "Easy Red Lentil Dal Soup",
        "servings": 6,
        "ingredients": [
            [1, "Tablespoon", "Canola oil"],
            [1, "each", "Onion, diced"],
            [4, "cloves", "Garlic, minced"],
            [2, "Teaspoon", "Fresh ginger, grated"],
            [2, "Teaspoon", "Garam masala"],
            [1, "Teaspoon", "Cumin seeds"],
            [0.5, "Teaspoon", "Turmeric, ground"],
            [1, "pinch", "Cayenne pepper"],
            [2, "Cup", "Red lentils, dry split"],
            [6, "Cup", "Vegetable broth"],
            [1, "Cup", "Coconut milk, full-fat"],
            [14, "Ounce", "Diced tomatoes, canned"],
            [2, "Tablespoon", "Lemon juice"],
            [0.25, "Cup", "Cilantro, chopped"],
        ],
    },
    {
        "name": "Egg Drop Soup",
        "servings": 4,
        "ingredients": [
            [2, "each", "Eggs"],
            [6, "Cup", "Chicken broth"],
            [1, "Teaspoon", "Sugar"],
            [0.5, "Teaspoon", "Fresh ginger, grated"],
            [0.25, "Teaspoon", "White pepper, ground"],
            [0.5, "Teaspoon", "Sea salt"],
            [1, "each", "Green onion, sliced"],
            [1, "Tablespoon", "Cornstarch"],
            [3, "Tablespoon", "Water, cold"],
            [1, "Teaspoon", "Rice wine"],
        ],
    },
    {
        "name": "Everyday Low Carb Bread (Chia Almond)",
        "servings": 12,
        "ingredients": [
            [1, "Cup", "Quark"],
            [3, "each", "Eggs"],
            [1, "Cup", "Almond flour"],
            [2, "Tablespoon", "Coconut flour"],
            [3, "Tablespoon", "Psyllium husks"],
            [3, "Tablespoon", "Chia seeds"],
            [0.5, "Tablespoon", "Baking powder"],
            [0.5, "Teaspoon", "Salt"],
            [2, "Tablespoon", "Sunflower seeds"],
        ],
    },
    {
        "name": "Fried Wontons",
        "servings": 6,
        "ingredients": [
            [1, "Pound", "Ground pork"],
            [2, "each", "Carrots, chopped"],
            [5, "each", "Scallions, chopped"],
            [1, "Tablespoon", "Soy sauce"],
            [1, "Tablespoon", "Sesame oil"],
            [1, "Tablespoon", "Fresh ginger, minced"],
            [2, "cloves", "Garlic, minced"],
            [48, "each", "Wonton wrappers"],
        ],
    },
    {
        "name": "Instant Pot Garlic Parmesan Corn on the Cob",
        "servings": 4,
        "ingredients": [
            [4, "each", "Corn on the cob"],
            [1, "Cup", "Water"],
            [0.25, "Cup", "Butter, unsalted"],
            [2, "Tablespoon", "Parmesan cheese, grated"],
            [1, "Teaspoon", "Garlic, minced"],
        ],
    },
    {
        "name": "Ginger Pork Stir-Fry",
        "servings": 4,
        "ingredients": [
            [1, "Tablespoon", "Cornstarch"],
            [1, "Cup", "Orange juice"],
            [2, "Tablespoon", "Soy sauce"],
            [2, "cloves", "Garlic, minced"],
            [0.25, "Teaspoon", "Ginger, ground"],
            [1, "Pound", "Pork tenderloin, sliced"],
            [1, "Tablespoon", "Canola oil"],
            [1, "each", "Onion, sliced"],
            [0.25, "Pound", "Snow peas, fresh"],
            [0.5, "each", "Red bell pepper, julienned"],
        ],
    },
    {
        "name": "Steel-Cut Oat Bread (Signos)",
        "servings": 8,
        "ingredients": [
            [0.5, "Cup", "Steel-cut oats"],
            [2, "Cup", "Water"],
            [1, "Teaspoon", "Salt"],
            [2, "Tablespoon", "Olive oil"],
            [0.25, "Cup", "Oat flour"],
        ],
    },
    {
        "name": "Homemade Tomato Soup (Fresh Tomatoes)",
        "servings": 6,
        "ingredients": [
            [3, "Pound", "Tomatoes, ripe"],
            [4, "cloves", "Garlic, peeled"],
            [0.5, "each", "Onion, diced"],
            [0.5, "each", "Red bell pepper, diced"],
            [2, "Tablespoon", "Olive oil"],
            [0.5, "Teaspoon", "Basil, dried"],
            [0.5, "Teaspoon", "Oregano, dried"],
            [2, "Cup", "Chicken broth"],
            [2, "Tablespoon", "Fresh herbs, mixed"],
            [0.25, "Cup", "Parmesan cheese, shredded"],
            [0.5, "Cup", "Heavy cream"],
        ],
    },
    {
        "name": "Instant Pot Beans (No Soak)",
        "servings": 6,
        "ingredients": [
            [1, "Cup", "Dry beans"],
            [3, "Cup", "Water"],
            [1, "clove", "Garlic"],
        ],
    },
    {
        "name": "Hurst Beef 15 Bean Soup",
        "servings": 12,
        "ingredients": [
            [1, "package", "Hurst 15 Bean Soup mix, beef flavored"],
            [20, "Cup", "Water"],
            [0.75, "Cup", "Onion, chopped"],
            [1, "clove", "Garlic, minced"],
            [1.5, "Pound", "Beef stew meat"],
            [15, "Ounce", "Stewed tomatoes, canned"],
        ],
    },
    {
        "name": "Instant Pot Peanut Butter Cheesecake",
        "servings": 8,
        "ingredients": [
            [10, "each", "Peanut butter cookies"],
            [3, "Tablespoon", "Butter"],
            [16, "Ounce", "Cream cheese"],
            [0.67, "Cup", "Sugar"],
            [2, "each", "Eggs"],
            [0.33, "Cup", "Peanut butter"],
            [6, "each", "Peanut butter cups, mini"],
            [0.5, "Cup", "Heavy cream"],
            [4, "Ounce", "Chocolate, semi-sweet"],
        ],
    },
    {
        "name": "Instant Pot Lentil Soup",
        "servings": 4,
        "ingredients": [
            [1, "each", "Onion, chopped"],
            [1, "each", "Carrot, chopped"],
            [2, "each", "Celery stalks, chopped"],
            [3, "cloves", "Garlic, minced"],
            [1.5, "Cup", "Green lentils, dry"],
            [14.5, "Ounce", "Diced tomatoes, canned"],
            [2, "Teaspoon", "Thyme, fresh"],
            [1, "Teaspoon", "Italian seasoning"],
            [4, "Cup", "Chicken broth, low-sodium"],
            [4, "Cup", "Baby spinach"],
            [0.25, "Cup", "Parmesan cheese, grated"],
        ],
    },
    {
        "name": "Instant Pot Mac and Cheese",
        "servings": 6,
        "ingredients": [
            [1, "package", "Elbow macaroni"],
            [4, "Cup", "Water"],
            [1, "Teaspoon", "Salt"],
            [1, "Cup", "Heavy cream"],
            [1, "package", "Cheddar cheese, shredded"],
        ],
    },
    {
        "name": "Mexican Chipotle Pork and Beans",
        "servings": 8,
        "ingredients": [
            [3, "Pound", "Pork shoulder, boneless"],
            [2, "Teaspoon", "Kosher salt"],
            [0.5, "Teaspoon", "Black pepper"],
            [3, "Teaspoon", "Cumin, ground"],
            [7, "Ounce", "Chipotle in adobo"],
            [2, "Tablespoon", "Olive oil"],
            [1, "each", "Onion, chopped"],
            [4, "cloves", "Garlic, minced"],
            [0.25, "Cup", "Tomato paste"],
            [1, "Cup", "Orange juice"],
            [2, "Cup", "Chicken broth"],
            [2, "each", "Bay leaves"],
            [48, "Ounce", "Butter beans, canned"],
            [1, "Tablespoon", "Oregano, dried"],
            [1, "Teaspoon", "Coriander, ground"],
            [0.5, "Teaspoon", "Allspice, ground"],
        ],
    },
    {
        "name": "Mom's Pork and Beans",
        "servings": 8,
        "ingredients": [
            [1, "each", "Pork hock, smoked"],
            [2, "Tablespoon", "Olive oil"],
            [1, "each", "Onion, chopped"],
            [2, "each", "Carrots, chopped"],
            [3, "each", "Celery stalks, chopped"],
            [1, "each", "Bell pepper, chopped"],
            [6, "cloves", "Garlic, minced"],
            [2, "Tablespoon", "Tomato paste"],
            [3, "sprig", "Thyme, fresh"],
            [7, "Cup", "Water"],
            [60, "Ounce", "Mixed beans, canned"],
        ],
    },
    {
        "name": "Mongolian Beef (Taste of Home style)",
        "servings": 4,
        "ingredients": [
            [1, "Tablespoon", "Cornstarch"],
            [0.75, "Cup", "Chicken broth, reduced sodium"],
            [2, "Tablespoon", "Soy sauce, reduced sodium"],
            [1, "Tablespoon", "Hoisin sauce"],
            [2, "Teaspoon", "Sesame oil"],
            [1, "Pound", "Beef sirloin steak, sliced"],
            [1, "Tablespoon", "Olive oil"],
            [5, "each", "Green onions"],
            [2, "Cup", "Rice, cooked hot"],
        ],
    },
    {
        "name": "Orange Chicken Stir-Fry",
        "servings": 4,
        "ingredients": [
            [2, "Tablespoon", "Canola oil"],
            [2, "each", "Chicken breast, cubed"],
            [0.25, "Teaspoon", "Garlic salt"],
            [0.5, "Cup", "Orange juice"],
            [2, "Tablespoon", "Soy sauce"],
            [2, "Teaspoon", "Cornstarch"],
            [0.25, "Teaspoon", "Ginger, ground"],
            [1, "each", "Orange, sections"],
            [2, "each", "Green onions, sliced"],
        ],
    },
    {
        "name": "Orange Sheet Cake (Valencia)",
        "servings": 8,
        "ingredients": [
            [300, "Gram", "All-purpose flour"],
            [12, "Gram", "Baking powder"],
            [4, "each", "Eggs"],
            [0.5, "Teaspoon", "Salt"],
            [180, "Gram", "Sugar"],
            [220, "Milliliter", "Orange juice, fresh"],
            [140, "Milliliter", "Sunflower oil"],
        ],
    },
    {
        "name": "PF Chang's Mongolian Beef (Copycat)",
        "servings": 6,
        "ingredients": [
            [2, "Pound", "Beef steak, NY strip or flank"],
            [0.5, "Cup", "Cornstarch"],
            [0.5, "Cup", "Vegetable oil"],
            [2, "Tablespoon", "Vegetable oil"],
            [1, "Cup", "Soy sauce, low-sodium"],
            [1, "Cup", "Brown sugar"],
            [4, "cloves", "Garlic, minced"],
            [2, "Tablespoon", "Fresh ginger, minced"],
            [1, "Cup", "Water"],
            [1, "Tablespoon", "Rice vinegar"],
            [0.5, "Teaspoon", "Red pepper flakes"],
            [3, "each", "Green onions, sliced"],
        ],
    },
    {
        "name": "Instant Pot Pot Roast",
        "servings": 6,
        "ingredients": [
            [3, "Pound", "Chuck roast"],
            [1, "Tablespoon", "Olive oil, extra virgin"],
            [1, "each", "Onion, chopped"],
            [3, "cloves", "Garlic, minced"],
            [2, "Teaspoon", "Rosemary, chopped"],
            [1, "Teaspoon", "Thyme, chopped"],
            [3, "Tablespoon", "Tomato paste"],
            [2, "Tablespoon", "All-purpose flour"],
            [0.5, "Cup", "Red wine"],
            [3, "Cup", "Beef broth, low-sodium"],
            [1, "Tablespoon", "Worcestershire sauce"],
            [1, "Pound", "Baby potatoes, halved"],
            [4, "each", "Carrots, sliced"],
        ],
    },
    {
        "name": "Pozole Rojo",
        "servings": 8,
        "ingredients": [
            [2, "Pound", "Pork, cubed"],
            [6, "each", "Guajillo chiles, dried"],
            [30, "Ounce", "Hominy, canned"],
            [6, "cloves", "Garlic"],
            [1, "each", "Tomato"],
            [0.5, "each", "Onion"],
            [1, "Teaspoon", "Oregano, dried"],
            [1, "Teaspoon", "Cumin, ground"],
            [2, "each", "Bay leaves"],
            [2, "Cup", "Radish, chopped"],
            [8, "each", "Limes"],
            [4, "Cup", "Lettuce, chopped"],
            [40, "each", "Tortilla chips"],
            [0.25, "Cup", "Cilantro, chopped"],
            [1, "each", "Onion, chopped"],
        ],
    },
    {
        "name": "Russet Potato Soup",
        "servings": 12,
        "ingredients": [
            [6, "slices", "Bacon"],
            [6, "each", "Potatoes, russet"],
            [1, "each", "Onion"],
            [6, "Tablespoon", "Butter"],
            [6, "Tablespoon", "All-purpose flour"],
            [4, "Cup", "Chicken stock"],
            [3, "Cup", "Milk"],
            [3, "each", "Green onions"],
            [1.5, "Cup", "Cheddar cheese, sharp shredded"],
            [0.5, "Cup", "Sour cream"],
        ],
    },
    {
        "name": "Sesame Chicken",
        "servings": 4,
        "ingredients": [
            [1, "Pound", "Chicken thighs, boneless"],
            [1.5, "Teaspoon", "Peanut oil"],
            [2, "Tablespoon", "Sesame seeds"],
            [1, "each", "Scallion, sliced"],
            [2, "Tablespoon", "Soy sauce"],
            [2, "Teaspoon", "Sesame oil"],
            [1, "Tablespoon", "Sugar"],
            [1, "Tablespoon", "Honey"],
            [2, "Tablespoon", "Rice vinegar"],
            [1, "Tablespoon", "Fresh ginger, grated"],
            [1, "clove", "Garlic, minced"],
            [1, "each", "Eggs"],
            [3, "Tablespoon", "Cornstarch"],
        ],
    },
    {
        "name": "Slow Cooker Mississippi Stew",
        "servings": 7,
        "ingredients": [
            [1.75, "Pound", "Beef stew meat"],
            [1.5, "Pound", "Baby potatoes"],
            [0.25, "Cup", "All-purpose flour"],
            [1, "package", "Ranch dressing mix, dry"],
            [1, "package", "Brown gravy mix, dry"],
            [1, "Cup", "Peperoncini peppers"],
            [0.25, "Cup", "Pepperoncini brine"],
            [2, "Cup", "Water"],
            [2, "Tablespoon", "Butter"],
        ],
    },
    {
        "name": "Instant Pot Split Pea Soup",
        "servings": 6,
        "ingredients": [
            [0.25, "Cup", "Olive oil, extra virgin"],
            [1, "each", "Leek, sliced"],
            [1, "each", "Onion, chopped"],
            [3, "each", "Carrots, sliced"],
            [3, "each", "Celery stalks, sliced"],
            [3, "cloves", "Garlic, minced"],
            [1.5, "Cup", "Split peas, green dry"],
            [4, "Ounce", "Ham, diced"],
            [1, "Tablespoon", "Thyme, fresh"],
            [4, "Cup", "Chicken broth, low-sodium"],
            [2, "Tablespoon", "Lemon juice"],
        ],
    },
    {
        "name": "Steak Stir-Fry",
        "servings": 4,
        "ingredients": [
            [1, "Teaspoon", "Beef bouillon granules"],
            [1, "Cup", "Water, boiling"],
            [2, "Tablespoon", "Cornstarch"],
            [0.33, "Cup", "Soy sauce"],
            [1, "Pound", "Beef sirloin steak, sliced"],
            [1, "clove", "Garlic, minced"],
            [1, "Teaspoon", "Ginger, ground"],
            [0.25, "Teaspoon", "Black pepper"],
            [2, "Tablespoon", "Canola oil"],
            [1, "each", "Green bell pepper, julienned"],
            [1, "Cup", "Carrots, julienned"],
            [5, "each", "Green onions"],
        ],
    },
    {
        "name": "Sugar Snap Pea Stir-Fry",
        "servings": 4,
        "ingredients": [
            [1, "Pound", "Sugar snap peas"],
            [2, "Teaspoon", "Canola oil"],
            [1, "clove", "Garlic, minced"],
            [2, "Teaspoon", "Fresh ginger, minced"],
            [1.5, "Teaspoon", "Balsamic vinegar"],
            [1.5, "Teaspoon", "Soy sauce, reduced sodium"],
            [1, "Teaspoon", "Sesame oil"],
            [1, "dash", "Cayenne pepper"],
            [1, "Tablespoon", "Basil, fresh minced"],
            [2, "Teaspoon", "Sesame seeds, toasted"],
        ],
    },
    {
        "name": "Sweet and Sticky Crispy Beef",
        "servings": 5,
        "ingredients": [
            [1.5, "Pound", "Sirloin steak"],
            [1, "Cup", "Potato starch"],
            [1, "each", "Onion, small"],
            [2, "cloves", "Garlic"],
            [5, "slices", "Fresh ginger"],
            [1, "Tablespoon", "Soy sauce, light"],
            [0.75, "Cup", "Honey"],
            [1.5, "Cup", "Soy sauce, light"],
            [0.5, "Cup", "Water"],
            [1, "Tablespoon", "Hoisin sauce"],
            [0.5, "Tablespoon", "Rice vinegar"],
            [1, "Tablespoon", "Sesame oil"],
            [1, "Tablespoon", "Shaoxing wine"],
            [5, "Teaspoon", "Cornstarch"],
            [6, "Teaspoon", "Water, cold"],
            [2, "each", "Green onions"],
        ],
    },
    {
        "name": "Taco Chili (Hurst 15 Bean)",
        "servings": 10,
        "ingredients": [
            [1, "package", "Hurst 15 Bean Soup mix"],
            [10, "Cup", "Water"],
            [1, "Pound", "Ground beef"],
            [2, "package", "Taco seasoning"],
            [14, "Ounce", "Diced tomatoes, canned"],
            [10, "Ounce", "Enchilada sauce, canned"],
            [4, "Ounce", "Green chiles, canned diced"],
            [1, "each", "Sweet onion, chopped"],
            [2, "cloves", "Garlic, minced"],
            [1, "Teaspoon", "Salt"],
        ],
    },
    {
        "name": "Three Cheese and Bacon-Stuffed Pork Chops",
        "servings": 6,
        "ingredients": [
            [5, "each", "Pork chops, boneless thick"],
            [1, "Teaspoon", "Olive oil"],
            [0.5, "Cup", "Mozzarella cheese, shredded"],
            [0.5, "Cup", "Cheddar cheese, shredded"],
            [0.25, "Cup", "Parmesan cheese, grated"],
            [9, "slices", "Bacon, cooked crumbled"],
            [1, "package", "Cornbread stuffing mix"],
        ],
    },
    {
        "name": "Chicken Stir-Fry (Allrecipes)",
        "servings": 4,
        "ingredients": [
            [4, "Cup", "Water"],
            [2, "Cup", "White rice, dry"],
            [0.67, "Cup", "Soy sauce"],
            [0.25, "Cup", "Brown sugar"],
            [1, "Tablespoon", "Cornstarch"],
            [1, "Tablespoon", "Fresh ginger, minced"],
            [1, "Tablespoon", "Garlic, minced"],
            [0.25, "Teaspoon", "Red pepper flakes"],
            [1.5, "Pound", "Chicken breast, boneless skinless, sliced"],
            [2, "Tablespoon", "Sesame oil"],
            [1, "each", "Broccoli head, florets"],
            [1, "each", "Onion, chunked"],
            [1, "Cup", "Carrots, sliced"],
            [8, "Ounce", "Water chestnuts, canned, sliced"],
            [1, "each", "Green bell pepper, matchstick"],
        ],
    },
    {
        "name": "Cucumber and Avocado Sushi (Allrecipes)",
        "servings": 4,
        "ingredients": [
            [1.25, "Cup", "Water"],
            [1, "Cup", "Sushi rice, dry"],
            [3, "Tablespoon", "Rice vinegar"],
            [1, "pinch", "Salt"],
            [4, "each", "Nori sheets"],
            [0.5, "each", "Cucumber, strips"],
            [1, "each", "Avocado, sliced"],
        ],
    },
    {
        "name": "Bacon and Corn Griddle Cakes",
        "servings": 4,
        "ingredients": [
            [8, "slices", "Bacon, chopped"],
            [0.33, "Cup", "Sweet onion, chopped"],
            [1, "Cup", "All-purpose flour"],
            [2, "Tablespoon", "Chives, fresh chopped"],
            [1, "Teaspoon", "Baking powder"],
            [0.5, "Teaspoon", "Salt"],
            [0.125, "Teaspoon", "Cayenne pepper"],
            [0.67, "Cup", "Milk"],
            [1, "each", "Eggs"],
            [1, "Tablespoon", "Canola oil"],
            [1, "Cup", "Corn kernels"],
            [0.5, "Cup", "Monterey Jack cheese, shredded"],
        ],
    },
    {
        "name": "Baked Amaranth Pudding",
        "servings": 6,
        "ingredients": [
            [3, "each", "Eggs"],
            [1, "Cup", "Milk"],
            [0.5, "Cup", "Honey"],
            [2, "Cup", "Amaranth, cooked"],
            [0.5, "Cup", "Raisins"],
            [1, "Teaspoon", "Vanilla extract"],
            [1, "Teaspoon", "Lemon zest, grated"],
            [1, "Teaspoon", "Lemon juice"],
            [2, "Cup", "Water, boiling"],
        ],
    },
    {
        "name": "Creamy Au Gratin Potatoes",
        "servings": 6,
        "ingredients": [
            [4, "each", "Russet potatoes, sliced"],
            [1, "each", "Onion, sliced"],
            [3, "Tablespoon", "Butter"],
            [3, "Tablespoon", "All-purpose flour"],
            [0.5, "Teaspoon", "Salt"],
            [2, "Cup", "Milk"],
            [1.5, "Cup", "Cheddar cheese, shredded"],
        ],
    },
]


def main():
    names = sorted(
        f.name
        for f in PDF_DIR.iterdir()
        if f.suffix == ".txt" and f.name not in SKIP
    )
    if len(names) != len(RECIPES):
        raise SystemExit(f"count mismatch: {len(names)} files vs {len(RECIPES)} recipes")
    data = dict(zip(names, RECIPES))

    lines = [
        "/**",
        " * Curated ingredient rows for Recipe/Text/PDF/*.txt (extracted from Recipe/PDF).",
        " * Keys use prefix PDF/ relative to Recipe/Text. See RecipeConversion.md §6.",
        " * Skipped reference PDFs (manuals / collections): DUO manual, IP_for_Beginners, Indian, Vegetable, Salads.",
        " */",
        "export default {",
    ]
    for key in sorted(data.keys()):
        entry = data[key]
        k = "PDF/" + key
        lines.append(f"  {json.dumps(k)}: {{")
        lines.append(f"    name: {json.dumps(entry['name'])}, ")
        lines.append(f"    servings: {entry['servings']}, ")
        lines.append("    ingredients: [")
        for row in entry["ingredients"]:
            q, m, name = row
            if isinstance(q, float) and q == int(q):
                q = int(q)
            lines.append(f"      [{q}, {json.dumps(m)}, {json.dumps(name)}],")
        lines.append("    ],")
        lines.append("  },")
    lines.append("};")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("Wrote", OUT)


if __name__ == "__main__":
    main()
